"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Circle_1 = require("./Circle");
var Shape_1 = require("./Shape");
var Rectangle_1 = require("./Rectangle");
var myShape = new Shape_1.Shape(10, 15);
var myCircle = new Circle_1.Circle(5, 10, 20);
console.log(myShape.getInfo());
console.log(myCircle.getInfo());
var myRectangle = new Rectangle_1.Rectangle(0, 4, 2, 3);
console.log(myRectangle.getInfo());
